import type { Metadata } from "next";
import ProviderWrapper from '../components/ProviderWrapper';
import "./globals.css";
import PopupManager from "@/components/shared/PopupManager";

export const metadata: Metadata = {
    title: "Travel Together",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <link
                href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
                rel="stylesheet"
            />
        </head>
        <body className="antialiased bg-gradient-to-b from-[#C2E59C] to-[#64B3F4] font-poppins">
        <ProviderWrapper>
            {children}
            <PopupManager />
        </ProviderWrapper>
        </body>
        </html>
    );
}
