import { FC, ReactNode } from 'react';
import type { Metadata } from 'next';
import ProviderWrapper from '@/components/ProviderWrapper';
import PopupManager from '@/components/shared/PopupManager';
import './globals.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Travel Together',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <head></head>
      <body
        className={`antialiased bg-gradient-to-b from-[#C2E59C] to-[#64B3F4] ${poppins.className}`}
      >
        <ProviderWrapper>
          {children}
          <PopupManager />
        </ProviderWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
